name: CI-CD
on:
  push:
    branches : ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Obter Código"
      - run: echo "Executar Docker Build"
      - run: echo "Enviar a Imagem Docker para o DockerHub"
  CD:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Obter Código"
      - run: echo "Executar Docker Build"
      - run: echo "Enviar a Imagem Docker para o DockerHub"
