name: CI-CD
on:
  push:
    branches : ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo Codigo
        uses: actions/checkout@v4
      - name : Executando Docker Login
        uses : docker/login-action@v3.4.0
        with :
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name : Construindo Imagem Docker
        uses : docker/build-push-action@v6.15.0
        with :
          context : ./src
          push : true
          file : ./src/Dockerfile
          tags : vinibressanini/shop:2.0
      - run: echo "Enviar a Imagem Docker para o DockerHub"
  CD:
    needs : [CI]
    runs-on: ubuntu-latest
    steps:
      - name : Obtendo Codigo
        uses : actions/checkout@v4
      - name : Configurando kubeconfig
        uses : azure/k8s-set-context@v4
        with : 
          method : kubeconfig
          kubeconfig : ${{secrets.K8S_KUBECONFIG}}        
      - name : Apply Deployment
        uses: Azure/k8s-deploy@v5
        with:
          manifests: |
            k8s/deployment.yaml
          images: vinibressanini/shop:2.0
